title: About Anya Choudhary
author: Anya Choudhary
email: achoudhary1@ebnet.org
description: >  My name is Anya Choudhary. I plan on studying environmental engineering in college. I have another blog about sustainability in the fashion industry. I love travelling and have been to over 20 countries.

# social links
twitter_username: ChoudharyAnya
github_username:  coder-anya7850

show_excerpts: true # set to false to remove excerpts on the homepage
